trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureKeyVault@2
  displayName: Azure Key Vault
  inputs:
    azureSubscription: 'myserviceconnection'
    KeyVaultName: 'myazurevault2000'
    SecretsFilter: '*'
    RunAsPreJob: false
- task: CmdLine@2
  displayName: Create file
  inputs:
    script: 'echo $(mysecret) > secret.txt'
- task: CopyFiles@2
  displayName: Copy file
  inputs:
    Contents: secret.txt
    targetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Publish Artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'